// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKoiYuBhHTGuaD-c3pNDEOrO7nWjJlsJM',
    appId: '1:912069233376:web:64ca003ce8f0f1c3ec9e85',
    messagingSenderId: '912069233376',
    projectId: 'ms-multi-store',
    authDomain: 'ms-multi-store.firebaseapp.com',
    storageBucket: 'ms-multi-store.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2IugjMSUhuH503pS4QOgNQ1k3jZHT0hA',
    appId: '1:912069233376:android:151c42dd4ed7c99cec9e85',
    messagingSenderId: '912069233376',
    projectId: 'ms-multi-store',
    storageBucket: 'ms-multi-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLB3AcbI5zEck5q8eyJJqY7Ljj4hwX3kM',
    appId: '1:912069233376:ios:9797cc9bc4540499ec9e85',
    messagingSenderId: '912069233376',
    projectId: 'ms-multi-store',
    storageBucket: 'ms-multi-store.appspot.com',
    androidClientId: '912069233376-ijphg6dk4m83eqqi9iodca0cgi3u2pl0.apps.googleusercontent.com',
    iosClientId: '912069233376-t33h75btic2fq0pj2i15grfappbfrpfe.apps.googleusercontent.com',
    iosBundleId: 'com.example.msMultiWebAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLB3AcbI5zEck5q8eyJJqY7Ljj4hwX3kM',
    appId: '1:912069233376:ios:4dc0b825f58b70ddec9e85',
    messagingSenderId: '912069233376',
    projectId: 'ms-multi-store',
    storageBucket: 'ms-multi-store.appspot.com',
    androidClientId: '912069233376-ijphg6dk4m83eqqi9iodca0cgi3u2pl0.apps.googleusercontent.com',
    iosClientId: '912069233376-hip2ct4gnv3vj91j175arcscfp4vugkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.msMultiWebAdmin.RunnerTests',
  );
}
